version: '3.7'

services:
    web:
        build:
            context: ./services/web_example_flask
            dockerfile: Dockerfile
        command: python3 run.py run -h 0.0.0.0
        ports:
            - 5000:5000
        env_file:
            - ./.env.dev
        depends_on:
            - db
    db:
        image: postgres:12-alpine
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.dev.db

volumes:
    postgres_data: