version: '3.7'

services:
    web:
        build:
            context: ./services/web_example_flask
            dockerfile: Dockerfile.prod
        command: gunicorn --bind 0.0.0.0:5000 application:app
        volumes:
            - static_volume:/home/app/web/application/static
        expose:
            - 5000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: postgres:12-alpine
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db
    nginx:
        build: ./services/nginx_example
        volumes:
            - static_volume:/home/app/web/application/static
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume: